Colorizando fotos - aula Awari
awarischool/colorizando-fotos pull request #32
Opened 2020-11-10 23:51 UTC by eduardouliana

Enviando arquivo de colorização de fotos da aula

2020-11-11 12:40 UTC, charoleizer commented on _notebooks/2020_11_10_naruto_rasengan.ipynb
> +        "deo.colorize('https://i.pinimg.com/originals/83/2c/b0/832cb07e69c38b1cdbb25ec86285fff2.jpg')"
este código apresenta um erro: `NameError: name 'deo' is not defined`

provavelmente faltou dar um play no código: `deo = DeOldify()`

2020-11-11 12:41 UTC, charoleizer approved these changes

2020-11-11 17:55 UTC, eduardouliana commented on _notebooks/2020_11_10_naruto_rasengan.ipynb
> +        "deo.colorize('https://i.pinimg.com/originals/83/2c/b0/832cb07e69c38b1cdbb25ec86285fff2.jpg')"
Verdade, provável que foi isso mesmo, muito obrigado haha

2020-11-13 00:21 UTC, RafaelWerner approved these changes
well played

2020-11-19 20:12 UTC, cassiasamp requested changes
Oi Eduardo, repare que o título não foi gerado após a execução da célula, então para fazermos um título, precisamos ter apenas `#` um espaço e o títlo e aí dar um `shift + enter` para executar o que está na célula. Também repetimos o processo de `shift+enter` para as células subsequentes. Veja se dá certo incluir o título e rodar as células e só submeter novamente.

2020-11-25 02:13 UTC, cassiasamp approved these changes

2020-11-25 02:13 UTC, merged